services:
  backend:
    container_name: pubsub-ui-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: pubsub-ui-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  firebase-emulator:
    container_name: pubsub-ui-firebase-emulator
    build:
      context: ./firebase-emulator
      dockerfile: Dockerfile
    profiles: ["dev"]
    ports:
      - "8085:8085"
    